resources:
  - url: /local/kiosk.js
    type: js
  - url: /local/custom-lovelace/thermostat-card/thermostat-card.js?v=0.1
    type: module
title: Lovelace Demo
views:
  - title: Home
    icon: mdi:heart
    id: kiosk
    panel: true
    cards:
      - type: custom:thermostat-card
        title: HVAC
        entity: climate.hvac